# Automatically generated by hassfest.
#
# To update, run python3 -m script.hassfest -p docker
FROM ghcr.io/home-assistant/qemux86-64-homeassistant:2024.2.1

# Synchronize with homeassistant/core.py:async_stop
ENV \
    S6_SERVICES_GRACETIME=240000

ARG QEMU_CPU

WORKDIR /usr/src

# Install gcc, make, and other build tools
RUN apk update && apk add --no-cache \
    gcc \
    g++ \
    gnu-libiconv \
    vim \
    make \
    cmake

## Setup Home Assistant Core dependencies
COPY requirements.txt homeassistant/
COPY homeassistant/package_constraints.txt homeassistant/homeassistant/
RUN \
    pip3 install \
        --only-binary=:all: \
        -r homeassistant/requirements.txt

COPY requirements_all.txt home_assistant_frontend-* home_assistant_intents-* homeassistant/
RUN \
    if ls homeassistant/home_assistant_frontend*.whl 1> /dev/null 2>&1; then \
        pip3 install homeassistant/home_assistant_frontend-*.whl; \
    fi \
    && if ls homeassistant/home_assistant_intents*.whl 1> /dev/null 2>&1; then \
        pip3 install homeassistant/home_assistant_intents-*.whl; \
    fi \
    && if [ "${BUILD_ARCH}" = "i386" ]; then \
        LD_PRELOAD="/usr/local/lib/libjemalloc.so.2" \
        MALLOC_CONF="background_thread:true,metadata_thp:auto,dirty_decay_ms:20000,muzzy_decay_ms:20000" \
        linux32 pip3 install \
            --only-binary=:all: \
            -r homeassistant/requirements_all.txt; \
    else \
        LD_PRELOAD="/usr/local/lib/libjemalloc.so.2" \
        MALLOC_CONF="background_thread:true,metadata_thp:auto,dirty_decay_ms:20000,muzzy_decay_ms:20000" \
        pip3 install \
            --only-binary=:all: \
            -r homeassistant/requirements_all.txt; \
    fi

## Setup Home Assistant Core
COPY . homeassistant/
RUN \
    pip3 install \
        --only-binary=:all: \
        -e ./homeassistant \
    && python3 -m compileall \
        homeassistant/homeassistant

RUN wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub \
    && wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.35-r0/glibc-2.35-r0.apk \
    && wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.35-r0/glibc-dev-2.35-r0.apk
RUN wget https://ftp.gnu.org/gnu/libiconv/libiconv-1.17.tar.gz

RUN apk add --force-overwrite glibc-2.35-r0.apk \
    && apk fix --force-overwrite alpine-baselayout-data \
    && apk add glibc-dev-2.35-r0.apk

RUN tar -xzvf libiconv-1.17.tar.gz \
    && cd libiconv-1.17 && ./configure --prefix=/usr/local/glibc --with-libiconv-prefix=/usr/local/glibc \
    && make \
    && make install

# Home Assistant S6-Overlay
COPY rootfs /

WORKDIR /config
